### ISSUE TITLE
Projection from mesh to rgb images incorrect

### ISSUE THREAD

**Issue by miguelriemoliveira** [lvonasek/tango#25]
Hi @lvonasek ,

as I told you I am back working on this. I am having some problems and wanted to get your opinion. So please, if you have some time read through this long (sorry) text and tell me what you think I am doing wrong.

My first task was to create a python script (that's my programming language) that would read an open constructor dataset, in particular:

1. The obj file in which the mesh is stored (given in your dataset folder, I am using the obj inside the dataset folder, I assume it is the non-simplified mesh)
2. The set of jpg rgb image files and corresponding txt files indicating the camera pose for each image (given in your dataset folder, in #20 you told me how they work)
3. The rgb camera's intrinsic parameters (I was not sure here, see bellow)
4. The per image ply or depth map (did not get this far yet)

I implemented the code reading all this stuff. As far as I can tell it should be working. To verify, what I do is to project the triangles in the mesh (1) to all the images described in (2). 

To get a better feeling, I select only a few triangles on the mesh which belong to an object (i.e. a door or a book), that is, I create a new mesh with meshlab by erasing all other faces,  and see if those triangles are well projected.

The odd thing is that they seem to be correctly projected for some images and incorrectly projected for others ... here's an example 

![screenshot from 2018-05-29 10-50-46](https://user-images.githubusercontent.com/11350998/40651673-32f09a12-632e-11e8-9c8b-71d6f25bf544.png)

... the object is the red book. For some images, e.g. 5,8,14,19,20 the projection seems ok. For others, e.g. 28,32,38 the triangles are just not well aligned with the book.

I see some reasons that could explain why this is not working, can you tell me your opinion?

a. There is something wrong with the timestamps -> It could be that, for some images the sync between the time of capturing the image and the time of getting the camera pose would fail. However, since it is the images which are close that are always wrong, it does not seem like a random unaligned timestamp problem.
b. I am doing something wrong with the projection -> It is very likely but I don's understand why the projection works for some images and not others ... In any case, my next step should be to  try to implement the projection as explained in #19 
c. I am getting the wrong intrinsics -> long explanation, see bellow. 

As for c. what I did was to use an app called "TangoROSStreamer" to publish camera_info_messages and then used it to create a yaml configuration file which I read. The content of the file is shown bellow. 

```yaml
image_width: 1920
image_height: 1080
camera_name: camera_color
camera_matrix:
  rows: 3
  cols: 3
  data: [1484.120151053405, 0.0, 982.1869163422028, 0.0, 1483.296808359715, 543.0569322723705, 0.0, 0.0, 1.0]
distortion_model: rational_polynomial
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.09370951394834764, -0.1640721737187069, 0.0, 0.0, 0.1224192868301668]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [1484.120151053405, 0.0, 982.1869163422028, 0.0, 0.0, 1483.296808359715, 543.0569322723705, 0.0, 0.0, 0.0, 1.0, 0.0]
```

This calibration is for a 1920x1080 image, which makes sense since the images you have in the dataset are this size. However, when I use the Google Constructor they have a calibration file for a 960x540 camera: 

```yaml
camera_id: TANGO_3DR_CAMERA_COLOR
camera_intrinsics:
  calibration_type: TANGO_3DR_CALIBRATION_POLYNOMIAL_2_PARAMETERS
  width: 960
  height: 540
  model: [742.060075526702, 741.648404179857, 490.843458171101, 271.278466136185]
  distortion: [0.0937095139483476, -0.164072173718707]
camera_extrinsics:
  orientation: [-0.706785140012307, 0.707372138513566, 0.00647751405612829, 0.00612089243330192]
  translation: [-0.0178448539838816, 0.00721245490079159, -0.00481233577874809]
```

... my guess is that they use the camera at half the resolution. Do these values make sense for you ... do you have similar values?

Thanks in advance,
Miguel

**Comment by lvonasek** [comment]
Hi,

1. yes it is not simplified mesh

Google Constructor is saving camera frames as PNG (or PNM I am not sure). They had to decrease resolution because their dataset was getting very big (e.g. 1GB/1minute). The calibration from TangoROSStreamer looks for me familiar.

What I think it can be mistake is mismatching ortho-perspective projection. If you just transform vertex by matrix you get ortho matrix but the camera image is perspective.

After transfering vertex v into image coordinates (vec4 uv = world2uv * vec4(x,y,z,1)) you have to do perspective dividion which is normally uv /= abs(uv.w) but in your transform was no projection matrix, also you have to convert it this way uv /= abs(uv.z * uv.w) - just like it was discribed in https://github.com/lvonasek/tango/issues/19 (I am not sure if uv.z should not be without abs to have correctly sign of z coordinate).

I guess that some images were projected correctly because the distance from camera to point was 1 meter and then abs(1.0 * uv.w) == abs(uv.z * uv.w).

Hopefully this helps

Lubos

**Comment by miguelriemoliveira** [comment]
Hi @lvonasek ,

thanks for the clarifications. I will see if I can make it work and get back to you.

Regards,
Miguel

**Comment by miguelriemoliveira** [comment]
Hi @lvonasek ,

I am still struggling with making this work. I have implemented as you suggest but I still don't get good results. 

a couple of questions just to make sure I am not doing something wrong?

**1. Camera poses**

In #20 you told me that from a txt file like this

```
3
0.768300 -0.006883 -0.640053 0.000000
0.020602 -0.999158 0.035474 0.000000
-0.639758 -0.040441 -0.767511 0.000000
-0.293721 0.007573 0.122499 1.000000
-0.763887 0.005422 0.645327 0.000000
-0.025907 0.998901 -0.039059 0.000000
-0.644830 -0.046555 -0.762907 0.000000
-0.283288 0.007842 0.118334 1.000000
-0.029717 0.998833 -0.038075 0.000000
-0.760676 0.002113 0.649128 0.000000
0.648451 0.048252 0.759725 0.000000
-0.254234 0.000720 0.096176 1.000000
248.445531
```

This is rgb camera transform 
```
0.768300 -0.006883 -0.640053 0.000000
0.020602 -0.999158 0.035474 0.000000
-0.639758 -0.040441 -0.767511 0.000000
-0.293721 0.007573 0.122499 1.000000
```

This transform is from the global reference frame to the rgb camera's pose when the image was taken, correct?

The mesh (the obj file) you produce is also defined in this global reference frame? So if I need to project a triangle vertex from the mesh with coordinates given in the obj file I first need to put these obj coordinates into camera coordinates correct? That means multiplying the point coordinates by the global frame to the camera frame transformation, right? Only after I multiply by the world2uv matrix correct?

**2. Are these poses before or after the optimization**

Because if they are before that could explain the small projection errors ...

**Comment by miguelriemoliveira** [comment]
Hi again,
just to add to what I said. I computed the projection (pixel or texture coordinates) in 3 different ways. Always the same result. So now I am starting to wonder if there is another problem somewhere ...

**Comment by lvonasek** [comment]
I have no idea, I tried myself to project 3d vertices into image and it is working for me:
https://youtu.be/cLk5rxXKbaE
You can take a look into code, I put it into this repository.

**Comment by miguelriemoliveira** [comment]
Hi Lubos,

first of all sorry for the late reply. I thought that, with the end of my classes I would have more time, but I have several M.Sc. students asking me to revise their thesis proposals and this is taking a lot of my time.

Anyway, I saw your tutorial video and its really helpful. Thank you for that. I also downloaded, compiled and tried out your dataset_viewer tool, which is quite nice.

I have used your dataset viewer tool to inspect my "red book" dataset and compared it with my projection of triangles to the image. Here are the images:

In your case, you project the image information to the 3D mesh. The top left corner of the book is not well aligned, which is why you map red color to portions of the table surface.

![dataset_viewer](https://user-images.githubusercontent.com/11350998/41035559-eef7a3ca-6984-11e8-8328-c9d5763cdde9.png)

In my case, I do the opposite - I project the 3D meshes vertices to the image. We can also see the mesh (I used only the triangles which correspond to the book) miss-aligned with the book. This would result, as in your case, in painting a part of the table with red color from the top left corner of the book.

![miguels_viewer](https://user-images.githubusercontent.com/11350998/41035567-f6e1f0f4-6984-11e8-813f-3758d780bba0.png)

**So my conclusion (please tell me if you agree) is that my projection is being well done, since It returns the same results as in your case**. I am closing this issue. Thanks for all your support.

Just a side note: from what I understood, you are not using the compensation of distortion parameters of the camera's lens.  See [opencv](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#), the x'' and y'' equations. 

If you are saving the undistored rgb images (see [this](https://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html#void%20undistort(InputArray%20src,%20OutputArray%20dst,%20InputArray%20cameraMatrix,%20InputArray%20distCoeffs,%20InputArray%20newCameraMatrix))) then you don't need to do the distortion correction while doing the projection. However, if you are just saving the raw rgb images, then you should do the distortion correction. 

I am not sure if the tango rgb camera has a lot of distortion (the numbers are bellow) so this effect could be minimal or not.

```
distortion_model: rational_polynomial
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.09370951394834764, -0.1640721737187069, 0.0, 0.0, 0.1224192868301668]
```

Can you confirm which images you are saving (raw or undistorted)?

If you want I can do a study (in a new issue) of the impact of using these distortion values versus not using them, just to assess if they are really important. That's the least I could do after you helped me so much.

In any case I will close this issue.

Regards,
Miguel
